### ISSUE TITLE
Link styles are not AA compliant

### ISSUE THREAD

**Issue by nowarkdev** [sky-uk/nowtv-styleguide#103]
> Thanks for letting us know about an Issue!
 > Please make sure you click the contribution guidelines link above, then fill out the blanks below

Short description of the issue

## Current behaviour:

 - Link colours fail required contrast ratio for AA compliance

![screen shot 2016-02-23 at 14 45 22](https://cloud.githubusercontent.com/assets/12642254/13255023/fe6447b2-da3b-11e5-8218-707444212779.png)

**Comment by peter-mouland** [comment]
cool - good to know. Will get Jamie or Vick etc to take a look.

ps, could you let us know who you are by tagging yourself?

**Comment by nowarkdev** [comment]
Apologies @peterthompson @alexnaish

**Comment by nowarkdev** [comment]
Closing this issue as the related PR has been merged.

@andhapp @PLAGR34GTT
