### ISSUE TITLE
Error validation messages are too close to the input elements

### ISSUE THREAD

**Issue by nowarkdev** [sky-uk/nowtv-styleguide#108]
## Current behavior/Screenshot:

![current-error-padding](https://cloud.githubusercontent.com/assets/12642254/13257574/570e519a-da47-11e5-987a-b1b63c5347f6.png)

## Expected behavior/Screenshot:

![required-error-padding](https://cloud.githubusercontent.com/assets/12642254/13257578/5c2beb42-da47-11e5-8677-d1e04a525324.png)

@alexnaish @peterthompson

**Comment by ldabiralai** [comment]
Closing as the PR has been merged
