### ISSUE TITLE
monitoring?

### ISSUE THREAD

**Issue by peter-mouland** [sky-uk/nowtv-styleguide#113]
just a thought.... as this is used in multiple projects do we want to monitor the file size (gzipped) of the js / css?

This would help with a performance budget (and prevent things like react being included in the js and multiple fonts in the css ) .

**Comment by alexjfno1** [comment]
We could do. How about we set up circle to push a version to akamai everytime we push to master then have a small app that just pings it and checks the filesize? 

If it goes over the threshold it posts in Slack or sends and email?

**Comment by peter-mouland** [comment]
could be that or a local build thing. hadn't thought it through yet :)

**Comment by alexjfno1** [comment]
Yeah, like a pre commit thing
