### ISSUE TITLE
use fonts from CDN

### ISSUE THREAD

**Issue by peter-mouland** [sky-uk/nowtv-styleguide#12]
We will push fonts to CDN but also keep them in git.

 - [x] push fonts to `/static` (i.e. not versioned)
 - [x] Pushing the fonts.css to a CDN should be done via a script which gets run manually (as it wont happen often).
 - [x] Update ReadMe to inform projects to use the CDN

**Comment by andrewmerrell** [comment]
Need to check with legal about what we need to do to secure the font.

**Comment by NowTV-Assurance** [comment]
@andrewmerrell Any Update on this?

**Comment by andrewmerrell** [comment]
I chased Laura again today, I'll go visit her if I don't hear anything back

**Comment by nowarkdev** [comment]
The styleguide is currently using 'Helivetica Neue' for the majority of fonts. Would resolving this issue revert them back to the NowTV fonts?

BTW, the NowTV fonts are already out there,
http://web.static.nowtv.com/ice/5.3.0/ui/css/polyatomic/nowtvtext-light.woff2

What are we hoping to achieve by means of 'security'?

**Comment by alexflorisca** [comment]
Sorry, who made the comment above?

Woff2 fonts aren't very useful for most browsers so we are using woff.  We'd also prefer to point to a static url which is not for iceberg ie. on `/fonts/` (similar discussion here: https://github.com/sky-uk/nowtv-react-toolkit/issues/29)

@andrewmerrell Have you heard anything back from Laura?

**Comment by andrewmerrell** [comment]
Just caught Laura, she is going to send me the contract, oh what an interesting read that will be... Will report back once I've read it, but I fear we may be in the same situation as the last one and need to restrict it to the domains we use! We could potentially host the styleguide off part of the nowtv domain and proxy it through to heroku to circumvent the issue?

Will have a think but ideas welcome :)

**Comment by alexflorisca** [comment]
@andrewmerrell Any news?

**Comment by peter-mouland** [comment]
done in web-toolkit
