### ISSUE TITLE
breakpoint update discussion

### ISSUE THREAD

**Issue by peter-mouland** [sky-uk/nowtv-styleguide#127]
* The breakpoints we currently have are fixed to 'device-type' naming.  This has the downside of making people link the breakpoint with the device (in design world and dev).  A widely used convention is to use things like 'small', 'medium' etc.  

 * We currently only have 2 mixins which both use 'min-width'.  We currently have use cases where we want to show certain things only on the mobile.  I would like to propose the use of more mixins to allow this use case.  We could do it in our project but as this mixin like this is already being used in the navigation i think there is a case to standardise it across projects.

Chris Coyier talks about his approach here : http://codepen.io/chriscoyier/post/codepens-css
(not that I think naming break-points after bears is quite necessary!)

thoughts?

**Comment by rogerfranklin2** [comment]
Not sure that changing to small medium etc would give us much to warrant a breaking change. I think that you would just end up saying things like 'medium is tablet' to the designer anyway. Also most designers ive worked with understand its width not device specific 

No problem with adding a mobile mixin if your team need it
