### ISSUE TITLE
toolkit-shame.scss?

### ISSUE THREAD

**Issue by peter-mouland** [sky-uk/nowtv-styleguide#128]
When would it be a good time to go over everyone's 'toolkit-shame.scss'?

Basically, we have a file which includes overrides for the toolkit.  It would be good to collate this hacks and see if there are any repeated cases which would benefit from  'modifiers'.

**Comment by benstokoe** [comment]
Why do you have a shame file anyway?

**Comment by peter-mouland** [comment]
We put things in it which are either waiting for PRs to be accepted or overrides we need. Currently we 'display:block' on buttons ( to centre align them) and give buttons a better 'focus' state.  It would be good to know if anyone else do things like this - the override might be useful to set as defaults within the style-guide
