### ISSUE TITLE
crossbrowser checklist

### ISSUE THREAD

**Issue by peter-mouland** [sky-uk/nowtv-styleguide#129]
I'm not sure if all components (including the react side of things) have been fully tested on all supported browsers.

This is probably an important part of the style-guide (to be cross browser compatible), we should probably go through and mark off which components have been tested in which browsers.  We could either add browser-badges to each component within the docs or by create a complete list here.

**Comment by rogerfranklin2** [comment]
Sounds good to me, also good to see what the minimum set of browsers we need to support are. 

I think before we were doing last 2 versions of IE FF Chrome Safari Android.

Not sure if anyone has any more they support or how many version of IE they are supporting
