### ISSUE TITLE
Update contributing.md

### ISSUE THREAD

**Issue by peter-mouland** [sky-uk/nowtv-styleguide#131]
If we are able to give stronger guidelines for contributing (i.e. 2 paces instead of tabs, always use colour variables) It will make accepting/rejecting PR's quicker.  It also ensure there are no repeated discussions that are based on individual coding-style preferences.  Any rejected PR's wont be or feel personal which will help maintain the agreed standards in the future

feel free to add rules or ideas below!

**general**
 * Use the `.editorconfig` (this will ensure your IDE plays nicely with things like 2 Spaces (not tabs)
 * Components should work without requiring 'build' setup changes
   * i.e. Components can be *enhanced* with webpack updates but updates must not be mandatory
 * Full component functionality should be documented and demo'd
   * This could be an explicit demo, i.e. one for each option and colour etc
   * or preferably, the default is demo'd and the ability to change options on the fly is provided

**HTML**
 * Ensure the component class names are prefixed with `n-`
 * Each component should be completely wrapped with a `n-component-name` i.e.
```HTML
/* 😡 */
  <div class='component-container'> ... </div>
/* 😡 */
  <div class='component'> ... </div>
  <div class='component-label'> ... </div>
/* 😀 */
  <div class='component'>
    <div class='component__text'> ... </div>
    <div class='component__label'> ... </div>
  </div>
```

**React**
 * Components should always deconstruct props and apply any unused props to outer-most div
```JS
const { position, classname, label, ...props } = this.props;
return (<div {...props}> ... </div>)
```

**CSS**
 * Class names should always match the component name
 * Do not add new colours (unless agreed by design)
 * Always use the provided colour variables
 * Use BEM

**Cross Browser Checking**
 * Latest 2 Chrome on latest windows + mac
 * Latest 2 Firefox on latest windows + mac
 * Latest Safari on latest mac and iOS
 * IE10 + on Latest Window

**Accessibility Checking**
  * Keyboard users (tabbing etc)
  * Screen readers users with Voice-Over

**Comment by tomatau** [comment]
To ensure every PR adds value that doesn't get lost, it makes sense to always submit a failing test that works only passes with the code change.
