### ISSUE TITLE
Remove iOS shadows on text inputs

### ISSUE THREAD

**Issue by nowarkdev** [sky-uk/nowtv-styleguide#141]
## Current

![img_0001](https://cloud.githubusercontent.com/assets/12642254/13782790/7b9dc868-eac0-11e5-9af4-afa569dea03b.jpg)

## Expected

![img_0002](https://cloud.githubusercontent.com/assets/12642254/13782798/86ec5d4c-eac0-11e5-83c0-9134fdd6a4e1.jpg)

**Comment by peter-mouland** [comment]
sorry, who is this?

**Comment by nowarkdev** [comment]
@peterthompson
