### ISSUE TITLE
Move this to public NPM

### ISSUE THREAD

**Issue by ldabiralai** [sky-uk/nowtv-styleguide#34]
I shouldn't have to login to npm to install this as a dependency seeing as it's public on github.

I think this should also apply to [nowtv-react-toolkit](https://github.com/sky-uk/nowtv-react-toolkit) but there's already a discussion about that over there.

**Comment by peter-mouland** [comment]
sound logic :+1:

**Comment by alexjfno1** [comment]
Agreed :) :+1:

**Comment by ldabiralai** [comment]
Done!
