### ISSUE TITLE
Header has margin-bottom which causes side effects on elements below

### ISSUE THREAD

**Issue by ldabiralai** [sky-uk/nowtv-styleguide#43]
Is this needed? Could this be removed?

My view is that components should deal with only the styles inside it's element, and not have anything which could affect positioning around it (so no margin).

What do people think?

**Comment by alexflorisca** [comment]
Yeah I agree, you can always set these properties in your app when consuming it if need be

**Comment by peter-mouland** [comment]
The designers agree it is hard to have a simple set of rules to describe horizontal spacing.
They were set here just so a page without 'extra' styles still looked ok, but i think if they are causing issues, removing them and forcing people to think about vertical styling themselves is fine. @ariley90 ?

**Comment by nowarkdev** [comment]
@roryp2 @james-maher 

:+1:

**Comment by ldabiralai** [comment]
Closed as the pr has now been merged
