### ISSUE TITLE
Stop using SVG as background-images

### ISSUE THREAD

**Issue by peter-mouland** [sky-uk/nowtv-styleguide#58]
Leaving SVGs as inline HTML enable us to style them using CSS.

Background images have the added complexity of making the scss hard to consume from the react-toolkit.

having icons which are used with set classes to display the bg-image restricts how the style-guide can be coded. i.e. each time an icon is applied to a component, a new PR is needed. If we allow people to include the icons as inline SVG, this opens up the toolkit immensely. They will be less code/complexity. There will be less PRs/Blockers for small changes.

Thoughts?

**Comment by ariley90** [comment]
Could you maybe show us an example with the header component? I helped build that and the generic icon class mixin that works with it. I worked on the assumption that we wouldn't need to modify the svgs. The header is flexible in that you add the generic icon class to the icon element. Once all the icons are in the style guide (currently awaiting assets) then PRs would not be needed for each variation of header. 

Also how would this effect the input validation states? Or are they a unique case?

I would be keen to improve this as I'm not especially a fan of using the background-image technique.

**Comment by peter-mouland** [comment]
With background images (as with the old header), the whole style-guide css is bigger for everyone - even when they don't use those icons.  Previously, the header included 2 icons for everyone.  The new header component allows inline SVGs (and bg-images).

The inputs do seem to be unique case.

**Comment by peter-mouland** [comment]
this is happening in https://github.com/sky-uk/nowtv-web-toolkit
