### ISSUE TITLE
Reset CSS

### ISSUE THREAD

**Issue by ldabiralai** [sky-uk/nowtv-styleguide#63]
Do we want a small reset css? 

We've been talking in our team about at least having box-sizing: border-box on all elements, seeing as we're assuming most people will be doing that for anything with padding anyway. The exact rules are obviously up for discussion. 

We are aware this could cause issues with already implemented styles elsewhere, but I think this is needed.

I think at some point we had normalise?

What do people think about this?

**Comment by ariley90** [comment]
I think this could be handy. In sales we use the grid and that comes with a version of normalise, maybe that's the one you had at some point? That's required for the grid to render correctly although it sneaks in a few additional rules from bootstrap which we can't seem to get rid of. Maybe we should move the grid into this project again, bringing with it the reset which we could split from the grid? This means you could only consume the reset if you wanted (assuming your using your 3 col layout) but we could make sure it still works nicely with the grid and all other components?

**Comment by alexjfno1** [comment]
I think normalise would be good to include into the styleguide. We could always have a sass variable like `$normalise: true` (default would be true) which could be overwritten by the client which determines if normalise is included in the styleguide.

Not sure if its a good idea to bring the grid into the style guide. Is sounds like it should be separate to me.

**Comment by ariley90** [comment]
Yeah I guess the main issue for us would be being able to manage where we use it as it may conflict with some of the settings of the grid's version so having a variable like that would be a good solution also. 

I'm not sure either so thought I would float the idea, maybe not them... :)

**Comment by peter-mouland** [comment]
[normalize.css](https://github.com/necolas/normalize.css) sounds fine to me.  It should live here in the style guide. 
The grid should take care of itself (not rely of resets) and set only the few it needs.

**Comment by peter-mouland** [comment]
added a PR https://github.com/sky-uk/nowtv-styleguide/pull/68

**Comment by tomatau** [comment]
Now that normalize has been included... it doesn't actually include `* { box-sizing: border-box }'... so it didn't solve our problem :D

**Comment by tomatau** [comment]
border box into base here: https://github.com/sky-uk/nowtv-styleguide/pull/75 please give it your thumbs

**Comment by peter-mouland** [comment]
this has been included now
