### ISSUE TITLE
when to contribute code?

### ISSUE THREAD

**Issue by peter-mouland** [sky-uk/nowtv-styleguide#65]
Just raising the question so that everyone is on the same page and everyones expectations are similar.

I have heard people say the are not contributing code because there component is not feature-complete yet or because they are planning to improve in the future.

Personally, i would prefer people to contribute sooner rather than later.  If it is not perfect, don't worry. Any contribution helps other teams and speeds up workflow.  If another team does use this component, then maybe both teams will benefit from the extra people working together to solve a common problem.

Thoughts?

**Comment by benstokoe** [comment]
But doesnt it have to be production ready?

**Comment by peter-mouland** [comment]
I don't think setting up branches and PRs to be reviewed early stops the code from being production ready.  Early feedback is good. Also others can benefit while the PR is being finished.

**Comment by peter-mouland** [comment]
Am closing this as it was raised before we had *many* meetings on a similar subject!
