### ISSUE TITLE
should we group inputs, checkbox etc under a `form` component?

### ISSUE THREAD

**Issue by peter-mouland** [sky-uk/nowtv-styleguide#70]
at the moment, inputs, checkboxes, radio buttons, drop-downs/selects are a bit out there in the open with out many rules around them.  Grouping them under a `form` component/header will bring some focus to this area.

**Comment by benstokoe** [comment]
Why is this a problem?

**Comment by peter-mouland** [comment]
just thought it might help the look of the demo pages (which are a bit large at the moment).

If so, it might influence how these components are coded. Form might be a parent component and end up with something like <form.input> And <form.toggle>.  Or not. worth discussing and thinking about though.
