### ISSUE TITLE
block element buttons

### ISSUE THREAD

**Issue by peter-mouland** [sky-uk/nowtv-styleguide#82]
buttons are currently `inline-block`, but have a `margin:0 auto`;

This suggests to me the buttons should be `block` so that they centre-align themselves.

Any objections to updating them to block?

**Comment by nowarkdev** [comment]
Don't mind, can't see a difference. @peterthompson

**Comment by peter-mouland** [comment]
closing due to multiple buttons can be on the same line - maybe add modifier --center if needed
