### ISSUE TITLE
layout - flexbox?

### ISSUE THREAD

**Issue by peter-mouland** [sky-uk/nowtv-styleguide#88]
it might be time to use flexbox. 
The max-width on the centre-content has been removed in the latest incarnation which causes the left header to look pretty bad in 800px wide tablets.

We can keep the min-width on the left and have a flexible right hand columns if we use flexbox

![screen shot 2016-02-17 at 1 38 39 pm](https://cloud.githubusercontent.com/assets/1727939/13111089/cb830e92-d57b-11e5-98d2-3ffdb36570fd.png)

@bdo @rogerfranklin2 @alexjfno1 thoughts?

**Comment by alexflorisca** [comment]
:+1: flexbox is the shit

**Comment by bdo** [comment]
@peter-mouland Not sure it's worth it. We should first fix your issue by adding a 15px padding in the header component or the now-layout-header. We do have this extra padding in our billing app already, so  it doesn't look too bad. I change our title to 'Check Service Status' to test it, but you can check for yourself at http://web.static.nowtv.com/billing/bill/prod/

![screen shot 2016-02-17 at 15 46 27](https://cloud.githubusercontent.com/assets/683020/13113083/e503c08e-d58d-11e5-8277-94549f8e7441.png)

**Comment by bdo** [comment]
![screen shot 2016-02-17 at 15 49 59](https://cloud.githubusercontent.com/assets/683020/13113139/1d2a5e1e-d58e-11e5-8708-a5ce0784c4e3.png)

**Comment by tomatau** [comment]
I'm gonna be the party pooper here as I've had frustrating experiences with flexbox for IE, and I'm not the only one: https://github.com/philipwalton/flexbugs

Although, yes flexbox is great when it works smoothly and designs are incredibly simple.

Addressing the style problem, I'd have thought can be solved by striking a balance between:
- the breakpoint widths
- assumed maximum copy length
- ratio between columns

Then one set of styles can work for all the scenarios with a simple grid and breakpoints.

**Comment by bdo** [comment]
Apologies it says I closed the issue. Must have done it by accident ...

**Comment by peter-mouland** [comment]
The original thinking was to make sure the left hand header never rolled onto 2 lines. Maybe they've removed that requirement. will see what the designers have to say!

**Comment by tomatau** [comment]
Spoke to Jamie and he says that that requirement isn't a real requirement but he's going to dig a bit deeper about the breakpoints and try them out with longer titles.
