### ISSUE TITLE
add release process

### ISSUE THREAD

**Issue by nowarkdev** [sky-uk/nowtv-styleguide#9]
@peter-mouland
 * The release process should tag a version number and push to gh-pages

How to do this in docs would be good, or better, as a npm command 
i.e. `npm run release` which would patch by default 
or
`npm run release --major` etc to automatically bump the version number accordingly

**Comment by nowarkdev** [comment]
How should the teams be made aware of new releases? Email to the DL, perhaps?

**Comment by peter-mouland** [comment]
Who are you?

Teams will be notified of new releases via gitHub.  As contributors (or by 'watching') the repo you will get notified of changes.

You just have to make sure you log in as yourself into GitHub and only watch repo's you care about to keep notifications down to a minimum.  If you have multiple users on the same machine you can setup a google chrome user (i signed up to chrome under my sky.uk email address - not my personal one!).  Then you can switch users quickly without having to keeping logging in and out.

**Comment by rogerfranklin2** [comment]
I think you are in the minority @peter-mouland of people who actually look at github notifications. Either an email or a slack channel would be better.

We don't want it to be a pain to work with these internal open source projects so would make sense to send notifications somewhere where people already look like email/slack

**Comment by alexjfno1** [comment]
I think @rogerfranklin2 is right about people not seeing GitHub notifications. Im only watching 5 or 6 projects and I'm getting 12 to 15 notifications a day and I find it quite easy to missing something. Slack sounds like a good idea and maybe a DL which has all the teams using the toolkit DL's on it.

**Comment by ldabiralai** [comment]
Agree with @rogerfranklin2 and @alexjfno1

Slack might be nicer, we could have a channel which is just dedicated for release notifications.

Slack is also easier to join and leave than a DL.

**Comment by peter-mouland** [comment]
thats cool -  i'm happy with using it but people currently do not check slack either in my experience.

**Comment by andrewmerrell** [comment]
Add documentation on how to b
